# Generated by Django 5.2.3 on 2025-07-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image_path',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
