# Generated by Django 5.2.3 on 2025-07-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
