# Generated by Django 5.2.3 on 2025-07-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredient_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
