# Generated by Django 5.2.3 on 2025-07-05 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('recipes', '0005_recipeingredient_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_path',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='images.image'),
        ),
    ]
