# Generated by Django 5.2.3 on 2025-07-05 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('recipes', '0006_remove_recipe_image_path_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='image_path',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='images.image'),
        ),
    ]
