# Generated by Django 5.2.3 on 2025-07-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplanrecipe',
            name='meal_type',
            field=models.PositiveIntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Dinner'), (3, 'Snack')]),
        ),
    ]
