# Generated by Django 5.2.3 on 2025-07-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0002_alter_mealplanrecipe_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplanrecipe',
            name='meal_type',
        ),
    ]
